-- trivia.events: root entity for a trivia event, owned by a user.
-- References slacker.public."AspNetUsers" for ownership.

CREATE SCHEMA IF NOT EXISTS trivia;

CREATE TABLE IF NOT EXISTS trivia.events (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(200) NOT NULL,
    description text NOT NULL,
    created_on timestamptz NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_on timestamptz NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    user_id text NOT NULL REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_events_user_id ON trivia.events (user_id);

COMMENT ON TABLE trivia.events IS 'Trivia events owned by a user.';
