-- trivia.rounds: a round within an event.

CREATE TABLE IF NOT EXISTS trivia.rounds (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(200) NOT NULL,
    event_id integer NOT NULL REFERENCES trivia.events (id) ON DELETE CASCADE,
    "order" integer NOT NULL,
    created_on timestamptz NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE INDEX IF NOT EXISTS ix_rounds_event_id ON trivia.rounds (event_id);

COMMENT ON TABLE trivia.rounds IS 'Rounds within a trivia event.';
