-- trivia.categories: a category within a round.

CREATE TABLE IF NOT EXISTS trivia.categories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(200) NOT NULL,
    round_id integer NOT NULL REFERENCES trivia.rounds (id) ON DELETE CASCADE,
    "order" integer NOT NULL,
    created_on timestamptz NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE INDEX IF NOT EXISTS ix_categories_round_id ON trivia.categories (round_id);

COMMENT ON TABLE trivia.categories IS 'Categories within a round.';
