-- trivia.questions: a question within a category.

CREATE TABLE IF NOT EXISTS trivia.questions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_text text NOT NULL,
    answer text NOT NULL,
    image_url text NULL,
    category_id integer NOT NULL REFERENCES trivia.categories (id) ON DELETE CASCADE,
    "order" integer NOT NULL,
    created_on timestamptz NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE INDEX IF NOT EXISTS ix_questions_category_id ON trivia.questions (category_id);

COMMENT ON TABLE trivia.questions IS 'Questions within a category.';
