-- trivia.teams: teams participating in a specific event.

CREATE TABLE IF NOT EXISTS trivia.teams (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(200) NOT NULL,
    event_id integer NOT NULL REFERENCES trivia.events (id) ON DELETE CASCADE,
    created_on timestamptz NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE INDEX IF NOT EXISTS ix_teams_event_id ON trivia.teams (event_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_teams_event_id_name ON trivia.teams (event_id, name);

COMMENT ON TABLE trivia.teams IS 'Teams participating in a trivia event.';
