-- trivia.team_points: points for a team in a specific round.

CREATE TABLE IF NOT EXISTS trivia.team_points (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id integer NOT NULL REFERENCES trivia.teams (id) ON DELETE CASCADE,
    round_id integer NOT NULL REFERENCES trivia.rounds (id) ON DELETE CASCADE,
    points integer NOT NULL,
    created_on timestamptz NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE INDEX IF NOT EXISTS ix_team_points_round_id ON trivia.team_points (round_id);
CREATE INDEX IF NOT EXISTS ix_team_points_team_id ON trivia.team_points (team_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_team_points_team_id_round_id ON trivia.team_points (team_id, round_id);

COMMENT ON TABLE trivia.team_points IS 'Point totals for a team per round.';
